### ISSUE TITLE
mongodb version

### ISSUE THREAD

**Issue by ORESoftware** [aheckmann/gridfs-stream#106]
A nice addition to the readme would be the minimum MongoDB version that this lib is compatible with? Unless I missed it in the readme, but I didn't see it.

**Comment by riaan53** [comment]
The minimum mongodb version is under the [please note](https://github.com/aheckmann/gridfs-stream#please-note) section :)

**Comment by ORESoftware** [comment]
yeah sorry, I think I saw it as soon as I opened this issue LOL
