### ISSUE TITLE
How do you set the bucket to write to and read from?

### ISSUE THREAD

**Issue by pateras** [aheckmann/gridfs-stream#24]
This is how I'm uploading and downloading files using gridfs-stream:

var fs = require("fs");
var gridStream = require("gridfs-stream");
var mongoose = require("mongoose");

exports.init = function(app, db)
{
    var grid = gridStream(db, mongoose.mongo);

```
app.post("/UploadFile", function(request, response)
{
    var file = request.files.UploadedFile;

    var meta = request.param("Meta");
    var name = request.param("Name");

    var stream = grid.createWriteStream(
    {
        filename: name,
        metadata: meta
    });

    fs.createReadStream(file.path)
    .on("end", function()
    {
        response.send({ Success: true });
    })
    .on("Error", function(error)
    {
        HandleError(error, response);
    })
    .pipe(stream);
});

app.get("/DownloadFile", function(request, response)
{
    var selector = request.param("Selector");

    response.writeHead(200, { "Content-Type" : "image/png"});
    grid.createReadStream({ filename: "FileUploadNamed" }).pipe(response);
});
```

}

It works perfectly, but I'd like to specify a bucket to write to and read from. How can I do that?

Thanks for this great package!

**Comment by cyrilchapon** [comment]
What do you mean "The root option".

Closing this ticket with a documented solution would have been a great idea.

**Comment by tjesposito** [comment]
In case anyone stumbles across this, found it in the type definitions, literally the option called 'root', this worked fine for me:

```
gfs.createWriteStream({
   filename: file.originalName,
   content_type: file.mimetype,
   mode: 'w',
   root: 'customBucket', /* customBucket.files, customBucket.chunks */
   metadata: {...}
})
```
