### ISSUE TITLE
Update file metadata

### ISSUE THREAD

**Issue by Faleij** [aheckmann/gridfs-stream#35]
I could not find a specific way to update metadata, so I used gfs.files.update as in a regular mongoDB update but it behaves like save and not update; it just saves the update data to the collection and removes the existing data.

**Comment by hoodsy** [comment]
@Faleij mind posting an example of what u ended up doing (if you still have it lying around)?

**Comment by Faleij** [comment]
I am sorry but I don't recall exactly what I ended up doing but you should be able to access the underlying native mongo collection by accessing the [`files`](https://github.com/aheckmann/gridfs-stream/blob/master/lib/index.js#L56) property of your Grid object. Using `files` you can then call native mongo client collection functions such as [update](http://mongodb.github.io/node-mongodb-native/2.2/api/Collection.html#update) I believe.

Non-tested Example:
```javascript
const gfs = Grid(db, mongo);
gfs.files.update(
  { 'metadata.name': 'My File' },
  { $set: { 'metadata.name': 'My Renamed File' } }
).then(console.log, console.error);
```

**Comment by hoodsy** [comment]
I seemed to try every variation, without much success. From gfs.files to
actually accessing the collection via gfs.db.collection('fs.files'), I
wasn't able to get a single query working, other than the built in
convenience methods (findOne, etc).

**Comment by Faleij** [comment]
```javascript
'use strict';

const mongo = require('mongodb');
const Grid = require('gridfs-stream');

// create or use an existing mongodb-native db instance.
// for this example we'll just create one:
const db = new mongo.Db('faleijsGfsTest', new mongo.Server("127.0.0.1", 27017));

// make sure the db instance is open before passing into `Grid`
db.open()
    // !!!!!!!!!
    // !WARNING! THIS DROPS THE CURRENT DATABASE
    // !!!!!!!!!
    .then(() => db.dropDatabase())
    .then(() => {
        const gfs = Grid(db, mongo);

        return new Promise((resolve, reject) => {
            gfs.createWriteStream({ filename: 'my_file.txt' })
                .once('finish', resolve)
                .once('error', reject)
                .end('hello world');
        })
            .then(() => gfs.files.findOne({ filename: 'my_file.txt'}).then(file => console.log('should find file:', !!file)))
            .then(() => gfs.files.update(
                { filename: 'my_file.txt'},
                { $set: { filename: 'my_renamed_file.txt' } }
            ).then(res => console.log('should have modified:', res.result.nModified === 1)))

            .then(() => gfs.files.findOne({ filename: 'my_file.txt'}).then(file => console.log('should not find: ', !file)))
            .then(() => gfs.files.findOne({ filename: 'my_renamed_file.txt'}).then(file => console.log('should find rename', !!file)))
    })
    .catch(console.error);
```

This example that I wrote just now works fine for me. (Latest mongodb and gridfs-stream on nodejs v6.4 and MongoDB 3.2)

**Comment by hoodsy** [comment]
Thanks for sharing! I must be doing something wrong, I'll take another
look. I'm also using Mongoose.

**Comment by Auggysg** [comment]
I've been trying to do this for a whole day and I finally found a solution that works for me.... @Faleij thank you thank you thank you!
