### ISSUE TITLE
error response function  ReadStream

### ISSUE THREAD

**Issue by Maxtermax** [aheckmann/gridfs-stream#41]
Hi I'm new using the GridFS-stream module I followed the documentation and I have managed to run successfully the function to insert files to mongodb "createWriteStream" but I have a problem with the function to read the "ReadStream" files and display them in the browser,i insert a video to the database and now I need to read the function "readstream" with the parameters and the range of _id

``` javascript
var readStream=gfs.createReadStream({
      _id:"53cbfcac709687fc16d7401b",
      range: {
         startPos:0,
         endPos:40233373
      }
});
```

also after researching on the internet I found that I had to wait until he had finished reading the entire video to be shown to the module express.js

``` javascript

readStream.on('open',function(){
       //start to read de video 
    console.log("start..");
});//open

readStream.on('data',function(chunk){
    console.log("loading...")
});//loading

readStream.on("end",function(){
  console.log("ready");
});//end 

 readStream.on('error', function (err){
   console.log(err);   
 });// if error 

```

at this point if I try to express it this way does not answer the request and stays loading forever

``` javascript
app.get("/file",function(req,res){
  readStream.pipe(res);//this way no response :(
});//get file video
```

I found the way to solve it by creating another instance "gfs.createReadStream"

``` javascript
app.get("/file",function(req,res){
       gfs.createReadStream({
     _id:"53cbfcac709687fc16d7401b",
     range: {
         startPos:0,
        endPos:40233373
      }
       }).pipe(res);//this way response  downloading the video but not showing what I need  
});//get file video
```

this way response  downloading the video but not showing what I need, but this way images shown That made ​​me believe that the problem was that it should specify the contentType video:

``` javascript
app.get("/file",function(req,res){
       res.header('Content-Type', 'video/mp4');
       gfs.createReadStream({
     _id:"53cbfcac709687fc16d7401b",
     range: {
         startPos:0,
        endPos:40233373
      }
       }).pipe(res);//this way response empty video
});//get file video
```

not if the act of creating a new object instance "gfs.createReadStream" affects how the code behaves then my main problem is to answer the video in a url something like:

[video file](https://v.cdn.vine.co/r/videos/F184C6C3601088988371424276480_2b53f186e8e.0.4.8649904460317250188.mp4?versionId=CmvIIrhvYF02A9yc46FdBiii2dC0jqBb)

here is all the code I have so far would be great if I could hechar one vistaso and suggest me something to solve the problem 
https://github.com/Maxtermax/testing_gridfs-stream
i hope you can help me thanks.

**Comment by zajca** [comment]
Is this really working?
I'm doing similar thing and is never played, chrome show default player but play button disappears
```
app.get '/video-stream/:name', (req,res)->
  global.gfs.findOne { filename: req.params.name},(err,file)->
    if err? or !file? then return res.send(404,'Not Found')
    readStream = global.gfs.createReadStream(filename: file.filename)
    res.header("Content-Type","video/mp4");
    res.header("X-Content-Type-Options", "nosniff");
    res.header("Accept-Ranges", "bytes");
    res.header("Content-Length",file.length);
    readStream.pipe res
```

**Comment by riaan53** [comment]
Hi @zajca ,

If you specify `accept-ranges: bytes` in the header it means that your server supports http 206 partial content request (byte serving). The client (browser/video) will then ask for a specific range that will be indicated in the request header so just pass it in the range param to the gridfs readstream and set the correct bytes and content length in the response header. You can see an example implementation in this PR: https://github.com/vsivsi/meteor-file-collection/pull/27

Also see http://www.codeproject.com/Articles/813480/HTTP-Partial-Content-In-Node-js for a more detailed explanation and examples.

Use the v1.x of gridfs-streams for this as it implements the new node style streams (streams2) for the correct flow control that is necessary for video streaming. See discussions in https://github.com/aheckmann/gridfs-stream/pull/47 

Hope it helps.

Regards,
Riaan

**Comment by zajca** [comment]
So I found this gist: https://gist.github.com/psi-4ward/7099001
and use it with gridfs-stream. requests looking fine but video won't play
```
app.get '/video-stream/:name', (req,res)->
  global.gfs.findOne { filename: req.params.name},(err,file)->
    if err? or !file? then return res.send(404,'Not Found')
    StreamGridFile(req,res,file.length,file._id)

StreamGridFile = (req, res,size,id) ->
  if req.headers['range']
    parts = req.headers['range'].replace(/bytes=/, '').split('-')
    console.log parts,size
    partialStart = parts[0]
    partialEnd = parts[1]
    start = parseInt(partialStart, 10)
    end = if partialEnd then parseInt(partialEnd, 10) else size - 1
    chunkSize = end - start + 1
    console.log 'Range ', start, '-', end
    res.writeHead 206,
      'Content-Range': 'bytes ' + start + '-' + end + '/' + size
      'Accept-Ranges': 'bytes'
      'Content-Length': chunkSize
      'Content-Type': 'video/mp4'
    readStream = global.gfs.createReadStream(
      _id: id
      range:
        startPos:start
        endPos:end
    )
    readStream.on 'data', (chunk)->
      start += chunk.length
      console.log start,end,start >= end
      if start >= end
          res.end()
        else
          res.write chunk
  else
    res.header 'Content-Type', 'video/mp4'
    res.header 'Content-Length', size
    readStream = global.gfs.createReadStream(_id: id)
    readStream.pipe res
```
console output
```
[ '0', '' ] 3572531
Range  0 - 3572530
261120 3572530 false
522240 3572530 false
783360 3572530 false
1044480 3572530 false
1305600 3572530 false
1566720 3572530 false
1827840 3572530 false
2088960 3572530 false
2350080 3572530 false
2611200 3572530 false
2872320 3572530 false
3133440 3572530 false
3394560 3572530 false
3572531 3572530 true

[ '3510293', '' ] 3572531
Range  3510293 - 3572530
3572531 3572530 true
```

**Comment by riaan53** [comment]
Can you try it with the mp4 from this page if you use chrome? http://camendesign.com/code/video_for_everybody/test.html

I just want to confirm that your encoding is correct. Otherwise can you create a sample repo? Then I will have a look. 

Also use pipe for the partial requests not just write, pipe implements flow control and `res.write chunk` just writes all the data at once.

**Comment by zajca** [comment]
OK, this version is working just fine. Thank for advice @riaan53
```
StreamGridFile = (req, res,size,id,contentType) ->
  if req.headers['range']
    parts = req.headers['range'].replace(/bytes=/, '').split('-')
    partialStart = parts[0]
    partialEnd = parts[1]
    start = parseInt(partialStart, 10)
    end = if partialEnd then parseInt(partialEnd, 10) else size - 1
    chunkSize = end - start + 1
    res.writeHead 206,
      'Content-Range': 'bytes ' + start + '-' + end + '/' + size
      'Accept-Ranges': 'bytes'
      'Content-Length': chunkSize
      'Content-Type': contentType
    global.gfs.createReadStream(
      _id: id
      range:
        startPos:start
        endPos:end
    ).pipe res
  else
    res.header 'Content-Type', contentType
    res.header 'Content-Length', size
    readStream = global.gfs.createReadStream(_id: id)
    readStream.pipe res
```

**Comment by riaan53** [comment]
Cool! Glad I could help.
