### ISSUE TITLE
High memory usage because of unbound internal buffering

### ISSUE THREAD

**Issue by triccardi-systran** [aheckmann/gridfs-stream#58]
By default there is no limit to the internal buffering to the _q data Array. This means that if the stream input is faster than the stream output (mongodb), then the nodejs process will grow unbound in RAM.

With the following test I reached 8.6GB in ram:
```bash
# create a large file
$ dd if=/dev/zero of=zero.10GB bs=10M count=1024
```

```javascript
var mongodb = require('mongodb');
var gridstream = require('gridfs-stream');
var fs = require('fs');

var filename = 'zero.10GB';

mongodb.MongoClient.connect('mongodb://localhost:27017/test', {}, function(err, db) {

  var start = process.hrtime();

  var gfs = gridstream(db, mongodb);
  var writestream = gfs.createWriteStream({
    filename: filename
  });
  fs.createReadStream(filename).pipe(writestream)
    .on('progress', function logProgress(position) {
      console.log('gridfs-stream write progress', position);
    })
    .once('close', function gfsDone() {

      var diff = process.hrtime(start),
          time = diff[0]*1e9+diff[1];
      console.log('gridfs-stream write complete for "%s", total time was %dns.',filename,time);

      db.close(function() {process.exit();});
    });
});
```

With option `limit: 1` (no buffering at all, the opposite extreme value) the nodejs process never uses more than 310MB in RAM, CPU load is also much lower (40s vs 100s), and the global time is only 7% slower (470s vs 438s).

With option `limit: 10` we use the same RAM and CPU load as with `limit: 1`, and are now only 2% slower than with no limit (447s vs 438s).

I don't think it's reasonable to have an unlimited default. It's probably never reasonable to have no limit on internal buffering: the nodejs Stream API already handles buffering issues itself (see Stream2 documentation) so there is no need to do all this.

A quick fix: set a sane default value for limit, like 10.

A cleaner fix: use Stream2 API (from node 0.10), use npm package `readable-stream` if you want to support older nodejs versions: just implement _write() (see http://nodejs.org/api/stream.html#stream_api_for_stream_implementors).

**Comment by Reggino** [comment]
V1.0.0 is just released with node 0.10 streams thanks to @riaan53 .

**Comment by triccardi-systran** [comment]
The new version is promising, but there is still an unbound internal buffering issue: 
When the connection is not open yet, unbound buffering is done here:
https://github.com/aheckmann/gridfs-stream/blob/048a033c6185b03c6cef92f14801fbca50d22522/lib/writestream.js#L127-L135

It should not call done() until the chunk has been written to gridfs, ie after the store open.

**Comment by riaan53** [comment]
Hi @triccardi-systran ,

Would you recommend to remove the buffering before store is open all together then? It usually only buffers 2-3 chunks before the store opens but obviously can take longer depending on where your db is hosted - if the gridtore does not open a error will occur and then the store will be closed. Currently it will only buffer while waiting for the sotre to open then done() is only called when the chunk is written.

**Comment by triccardi-systran** [comment]
Hi @riaan53 ,
Yes I recommend to never buffer internally unless strictly required (for example MongoDB GridStore does some internal buffering to align writes to the fixed chunk size, in this case it is required).
Why? Because node Stream2 already handles buffering, and it does this correctly (this is tunable with highWaterMark Stream option), see http://nodejs.org/docs/v0.10.36/api/stream.html#stream_buffering
Doing again another unnecessary buffering will disable the Stream2 one, and if not properly done can create issues, like this one: unbound buffering.

I understand that in practice the buffering is limited because the _store open is fast, but we never know (for example tcp can take some time to establish the connection, because of failing hardware on the network path, or slow mongodb server...), and we gain nothing to do the buffering ourselves: Stream2 will already do it and we thus have the performance benefit from it.

**Comment by riaan53** [comment]
Ok cool - it makes sense. I will remove the done() call before the store is opened so no buffering will take place. 

Please share any other issues/suggestions that you find.

**Comment by triccardi-systran** [comment]
`done` should be stored and called back when _open finishes, not just ignored.

**Comment by riaan53** [comment]
@triccardi-systran 

I have made the change - can you please review the it at https://github.com/riaan53/gridfs-stream/blob/master/lib/writestream.js#L122 ?

Thanks!

**Comment by triccardi-systran** [comment]
@riaan53
This seems to work, but I think it's strange to keep the `this._q`: we should at most buffer one chunk (and store its related `done` callback).
The current code is confusing: there is a queue of chunks, but only one `done` callback, and by chance there is no desynchronization between them (the current gridfs-stream 1.0.0 does have a desynchro: the current done() may be called for a previous chunk, this will probably break the highWaterMark Stream2 buffering control), and the code still handles _q.length > 1 with recursive call to _write.
Also, having _write() called some times externally with arguments, and other times internally without arguments is also confusing (many indirect tests in the code to check in which mode we are ( `if (chunk)`).

What I would do:
* in _write:
 * if not yet opened, store the whole arguments in a _delayedWrite member and just return.
 * else call _writeInternal with the same arguments, where _writeInternal would call _store.write with the chunk argument, and call done() argument when finished.
* in _open completion:
 * if _delayedWrite is set, call _writeInternal with all arguments from _delayedWrite.

Why moving the real _store.write() into another function? to keep the usual conventions on who calls _write, because _write and how it's called is part of the Stream2 API.

No more queue, no more "buffering" vocabulary: we just delay the first write until we are ready to process it.

I haven't thought about the `_destroying` state; although I don't understand what is the usefulness of public method `destroySoon`: compared to `destroy` it just writes some more chunks: it is useless unless the _store.close() is called (it isn't), isn't it?

**Comment by riaan53** [comment]
@triccardi-systran , it seem like a more elegant solution and will make more sense for someone to maintain later on as we dont need to queue/buffer anymore. Will give it a go tonight or tomorrow and work the _flush in as well that you mentioned in the other issue. 

Yes destroySoon will just write some more data. When calling destroySoon it sets _destroying and after the write is done it will do a _store.close() in the gridsotre write callback. I dont know the exact use case for this but I kept it as I do not want to break the API.

**Comment by triccardi-systran** [comment]
Oh ok, I didn't see the _store.close() was called in all cases, including when destroying.

Since it's 1.0.0 we could break the API and remove destroySoon: IMO it has really no value: there is no control of how many more chunks would have been written to GridFS (and the behavior has already changed with our buffering removed).

Also, always closing the _store is good to avoid GridFS chunks leaks, but it seems strange to me to write something invalid (because it misses parts of the data) on GridFS, and store nowhere the fact that it's invalid.

Maybe we could store an additional flag in metadata saying the stream write has failed; or maybe we could instead remove the temporary chunks (it's what does Amazon AWS S3: the upload is cancelled on error, and temporary data is deleted.) It could be an option of the stream, since both usage seem legit.

**Comment by riaan53** [comment]
Hi @triccardi-systran ,

I have made the changes as discussed above and in https://github.com/aheckmann/gridfs-stream/issues/63 . Its much `cleaner` and less error prone now which I like - thank you for the help I appreciate it.

Changes include:
 - Removed destroySoon
 - Inherit from FlushWritable and implemented _flush
 - Implemented _delayedWrite and _writeInternal
 - Removed all _q and buffers and updated comments

https://github.com/riaan53/gridfs-stream/blob/master/lib/writestream.js

Let me know what you think and if there are any other improvements or suggestions.

Thanks!

Regards,
Riaan

**Comment by triccardi-systran** [comment]
@riaan53 Reviewed and patched here: riaan53/gridfs-stream/pull/2

**Comment by riaan53** [comment]
@triccardi-systran Thank you so much! See my comments there as well. You can do the PR directly to aheckmann.

Regards,
Riaan

**Comment by Reggino** [comment]
@triccardi-systran I'ld be happy to merge in your changes if you would create a pull request.

**Comment by triccardi-systran** [comment]
@Reggino See #67
