### ISSUE TITLE
Get File information by passing _id as String

### ISSUE THREAD

**Issue by julb** [aheckmann/gridfs-stream#62]
Hi,

It can be useful to get the information of a file using its _id.

I did this in my method:

gfs.files.find({ _id: gfs.tryParseObjectId('54da7b013706c1e7ab25f9fa') }).toArray(function (err, files) {
        console.log(files[0]);
});

It would be easier to write it like this:
gfs.findOne({ _id: '54da7b013706c1e7ab25f9fa'}, function (err, file) {
        console.log(file);
});

What do you think of this ?

**Comment by Reggino** [comment]
This is added in v1.0.1 by @healiha 

Thanks for suggestion!
