### ISSUE TITLE
[Stream2] 'finish' event should be emitted only after `_store.close()`

### ISSUE THREAD

**Issue by triccardi-systran** [aheckmann/gridfs-stream#63]
See nodejs v0.10 documentation:
http://nodejs.org/docs/v0.10.36/api/stream.html#stream_event_finish

> When the end() method has been called, and all data has been flushed to the underlying system, this event is emitted. 

Currently when the 'finish' event is emitted, the data is not flushed to GridFS since the `_store.close()` has not finished yet.

See https://github.com/joyent/node/issues/7348 for a discussion around 'finish' and 'close' events in such cases ('close' event is not normalized in the API, so it's not the right solution).
At the end of the thread there is a workaround: https://www.npmjs.com/package/flushwritable

**Comment by riaan53** [comment]
Hi @triccardi-systran ,

I saw that behavior and thought that the writeable stream saw `gridfs-stream` as the underlying system so then the `finish` event makes sense - but the data is not flushed to the gridstore at that moment like you said. I will try the workaround you provided.

Thanks!

Regards,
Riaan

**Comment by triccardi-systran** [comment]
It should be fixed by PR #67
