### ISSUE TITLE
May I insert some fields when using createWriteStream

### ISSUE THREAD

**Issue by Kagamine** [aheckmann/gridfs-stream#70]
I want to put somethings when using createWriteStream
Can I put other fields with filename?

    var writestream = db.gfs.createWriteStream({
        filename: req.files.uploadImg.filename,
        blablabla: 12345
    });

**Comment by zentosNase** [comment]
same here :(

**Comment by kjunine** [comment]
Use `metadata` field.

https://github.com/aheckmann/gridfs-stream#createwritestream
http://mongodb.github.io/node-mongodb-native/1.4/api-generated/gridstore.html

**Comment by Reggino** [comment]
Thanks @kjunine
