### ISSUE TITLE
Reading the contents of a GFS directory?

### ISSUE THREAD

**Issue by kemalcany** [aheckmann/gridfs-stream#77]
Hello guys,

So createReadStream requires at least and _id or the filename to read the file from gfs. 

What happens if we don't know the filename (neither the _id) but we want to read a file giving a directory path as the root option instead?

To put it differently, is it possible to read the contents of a gfs directory? Does anyone have any idea?

Cheers!
K

**Comment by Reggino** [comment]
gfs doesn't do directories :-)
