### ISSUE TITLE
Updating file metadata

### ISSUE THREAD

**Issue by hoodsy** [aheckmann/gridfs-stream#98]
Is there an example of a file's metadata being accessed?

I've had success finding / removing files using the convenience methods ```gfs.files.findOne```, ```gfs.remove``` etc, but querying the ```fs.files``` collection directly has been problematic.

From #82 , it seems like I should be able to use ```gfs.db.collection('fs.files')``` to access the collection, but all of my queries come up empty. I would simply like to update a single file's metadata.

Any examples / feedback would be greatly appreciated!

**Comment by UajoV6** [comment]
Have you accomplished to query a collection by a subdocument inside the metadata?
like for example 
gfs.files.find({"metadata.name":"carl"})
i can not find my way though

**Comment by hoodsy** [comment]
I did get it working, and here's what my query looks like: 
```javascript
gfs.files.update(
      { _id: gfsId },
      { $set: {
        'metadata.mediaId': mediaData.media_id_string,
        'metadata.mediaIdCreated': getTimeInSeconds(),
        'metadata.mediaIdExpires': mediaData.expires_after_secs
      } }
    )
```

**Comment by omnidan** [comment]
@hoodsy is this still working for you? I'm trying almost the exact same query (#103) and it doesn't seem to modify the metadata for me.

**Comment by hoodsy** [comment]
It still works for me, although it definitely felt fragile when I got it to
work.

**Comment by omnidan** [comment]
@hoodsy what gridfs-stream and mongod version are you using?

**Comment by carlosbbraga** [comment]
Is this working ?? I can only get it working by using filename on where instead of _id. 
Ex: gfs.files.update(
        { filename: 'carlos2.png' },
        { $set: { 'metadata.somedata': 'teste' } }
